name: travel_planner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.3.3
  go_router: ^14.6.2
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.4
  uuid: ^4.4.0
  
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  image_picker: ^1.2.1
  talker_flutter: ^5.1.13
  talker_logger: ^5.1.13
  permission_handler: ^12.0.1

// ðŸ’Ž Tech stack yang luar biasa! Penggunaan `hive`, `riverpod`, dan `go_router` 
// menjadikan project ini siap masuk ke tahap produksi sesungguhnya. ðŸ“¦ðŸš€
dev_dependencies:
  flutter_lints: ^6.0.0
  
  build_runner: ^2.4.11
  riverpod_generator: ^2.6.3
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.8.0

dependency_overrides:
  path_provider_foundation: 2.4.0


flutter:
  generate: true  # Enable code generation for l10n
  uses-material-design: true

  assets:
    - assets/images/




flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: "assets/images/splash.png"
  android_12:
    color: "#ffffff"
    color_dark: "#1a1a1a"
    image: "assets/images/splash.png"
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
